//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MissingPersons.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MissingPerson
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string SecondName { get; set; }
        public string Surname { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string EyeColor { get; set; }
        public int Height { get; set; }
        public string DistinguishingMarks { get; set; }
        public System.DateTime LastSeenDate { get; set; }
        public string LastSeenPlace { get; set; }
        public string Picture { get; set; }
    }
}
